### ISSUE TITLE
wiki の scheduled tasks の Deploy Configuration の情報が古い

### ISSUE THREAD

**Issue by otsuka-kentaro** [metaps/genova#105]
最新の情報に修正お願いします。
https://github.com/metaps/genova/wiki/Deploy-configuration#scheduled-task

最新
```yaml
clusters:
  - name: production
    # Scheduled task configuration
    scheduled_tasks:
      - rule: sitemap_refresh
        expression: "cron(* * * * ? *)"
        # (Optional)
        enabled: true
        # (Optional)
        description: Greeting
        targets:
          - name: production
            # (Optional)
            depend_service: production
            containers:
              - name: container
                build:
                  context: ..
                  dockerfile: docker/rails/Dockerfile
            # Task definition path
            path: ./deploy/production.yml
            # "ec2" or "fargate" (Optional)
            launch_type: ec2
            # (Optional)
            desired_count: 1
            # (Optional)
            description: Greeting
            # Override task role (Optional)
            task_role: EcsTaskExecutionRole
            # CloudWatch Events IAM role (Optional)
            cloudwatch_event_iam_role: ecsEventsRole
            # (Optional)
            overrides:
            - name: app
              command:
                - "rake"
                - "sitemap:refresh"
              environment:
                - FOO: bar
```

変更:
```
scheduled_tasks/targets/enabled -> scheduled_tasks/enabled
scheduled_tasks/targets/enabled -> scheduled_tasks/description
scheduled_tasks/targets/containers 以下を array へ
```
