### ISSUE TITLE
AutoDeploy の機能が配列で指定できるが複数指定できない

### ISSUE THREAD

**Issue by otsuka-kentaro** [metaps/genova#166]
https://github.com/metaps/genova/wiki/GitHub-push-detect-deploy

yaml は配列で設定できるが、複数指定しても一番上のもののみdeployが走る。

**Comment by naomichi-y** [comment]
こちら再現出来ず。yamlのサンプルをください。

**Comment by otsuka-kentaro** [comment]
```
auto_deploy:
  - branch: release
    cluster: staging-app
    service: backend
  - branch: release
    cluster: staging-app
    service: worker
```

この yaml だと backend のみしか動きませんでした。
backend と worker 逆にすると worker のみ自動でデプロイされました。

**Comment by naomichi-y** [comment]
`services` パラメータを追加しました。今後 `service` は非推奨となります。
https://github.com/metaps/genova/wiki/GitHub-push-detect-deploy

```
auto_deploy:
  - branch: release
    cluster: staging-app
    service:
      - backend
      - worker
```
