### ISSUE TITLE
Slackデプロイにてリポジトリ単位でデプロイ権限設定できるように

### ISSUE THREAD

**Issue by koda-h** [metaps/genova#183]
- ver 3.0時はcluster単位の権限設定が可能
- リポジトリ単位でも権限設定可能なように対応して欲しい
  - 設定方法はclusterの権限設定に準じた形で問題ない

```
permissions:
  - policy: repository
    names:
      - spocile
    allow_users:
      - h-koda
  - policy: cluster
    names:
      - production-*
    allow_users:
      - naomichi_yamakita
```
