### ISSUE TITLE
Slackデプロイでalias利用時、デプロイ対象リストでサービス名が正しく表示されない

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#201]
settings.local.yml
```
github:
  repositories:
    - name: foo1
    - name: foo2
      alias: bar2
      base_path: .
```

bar2をデプロイするとき、デプロイ対象サービスにfoo1しか表示されない。
