### ISSUE TITLE
スケジュールタスクでdescription、enabledオプションが効かない

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#236]
enabledをfalseに指定してもタスクが無効にならない。

```
  scheduled_tasks:
    - expression: "cron(0 * * * ? *)"
      rule: staging-hourly
      enabled: false
```
