### ISSUE TITLE
genovaのアップグレード (3.2.0)

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#260]
## 環境変数から設定ファイルへの変数移行

`.env` で定義されていた一部の環境変数 (genovaの起動に関係しないもの) は `config/settings.yml` に移動します。
必要に応じて `config/settings.local.yml` で上書きしてください。

* `GENOVA_URL` -> `slack.console.url`
* `GITHUB_PEM` -> `github.secret_key`
* `GITHUB_SECRET_KEY` -> `github.secret_key`
* `SLACK_API_TOKEN` -> `slack.api_token`
* `SLACK_CHANNEL` -> `slack.channel`
* `SLACK_CLIENT_ID` -> `slack.client_id`
* `SLACK_CLIENT_SECRET` -> `slack.client_secret`
* `SLACK_VERIFICATION_TOKEN` -> `slack.vertification_token`
* `SLACK_HOST` -> 破棄
* `SLACK_PORT` -> 破棄

https://github.com/metaps/genova/pull/259/files#diff-e769bbb8c1ba3711c5403b424ed9c218ffafba7f1890ee394717196f28ff4540

## SSH秘密鍵の管理方法を変更

Gitアクセスに必要なSSHの秘密鍵は、genovaのディレクトリ下で管理する方針に変更しました
`GITHUB_PEM` で管理していた鍵の中身を `{GENOVA_HOME}/.ssh/id_rsa` として保存してください。変更後にファイルのパーミッションを `600` に更新が必要です。

## 自動デプロイのパラメータ変更

GitHub Actionsと連携した自動デプロイに対応しました。
従来もGitHub Webhookを利用することで自動デプロイはできましたが、`steps` パラメータが新たに追加されました。
サービスのほか、Run taskの実行も可能となっています。

`config/deploy.yml` に定義するパラメータは次のように書き換えてください。
```
# 以前までの記述方法
auto_deploy:
  - branch: release
    cluster: staging-app
    services:
      - frontend

# 新しい記述方法
auto_deploy:
  - branch: release
    steps:
      - cluster: staging-app
        resources
          - frontend
```
設定を保存後、genovaの再起動が必要です。

### 自動デプロイ対象のブランチをパターン一致で指定可能に

ブランチの指定に `*` (アスタリスク) が指定可能になりました。完全一致のほか前方一致が可能です。
https://github.com/metaps/genova/wiki/Deploy-configuration#auto-deploy
