### ISSUE TITLE
タスク定義パラメータの共通化

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#28]
複数のクラスタで同じタスク定義を利用したいが、一部パラメータ(メモリ、イメージ名など)だけ調整したい。

**Comment by naomichi-y** [comment]
構成が複雑化するので一旦クローズ。

**Comment by koda-h** [comment]
service(や run task) を定義する yml は、構成したい service 毎(run task毎)に作成する必要がある。
このとき、 service1 と service2 を構成するコンテナにおいて、ベースは同じであるため、 environment: の内容が同一になるということがある。
同一の environment: を複数ymlに記載することになり、更新漏れが発生する懸念がある。

なので、 environment: の内容がマージされるような機能がほしいです。
特定のファイルの特定のコンテナを指定してその environment: の内容が同一となる yml が生成されるような形でしょうか。

例えば
service.yml
```
container_definitions:
  - name: app
    environment:
      - name: COLUMNS
        value: 300
```
がある場合、
run_task.yml
```
container_definitions:
  - name: app
    environment:
      include:
        path: ./deploy/production/service.yml
       name: app
```
のように指定すると
```
      - name: COLUMNS
        value: 300
```
が environment: として構成されるようなイメージです。
