### ISSUE TITLE
Array parameters are merged when task_override is used

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#283]
Use `task_overrides` as follows.

`config/deploy/production.yml`
```
container_definitions:
  - name: app
    command:
      - bundle
      - exec
      - rails
      - "s"
      - "-b"
      - "0.0.0.0"
```
`config/deploy.yml`
```
clusters:
  - name: production
    run_tasks:
      greeting:
        containers:
          - name: rails
            build:
              context: ..
        path: ./deploy/production.yml
        task_overrides:
          container_definitions:
            - name: app
              command:
                - "bundle"
                - "exec"
                - "rails"
                - "s"
                - "-b"
                - "127.0.0.1"
```

In this case, command is executed like `["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "127.0.0.0.1"]`.
