### ISSUE TITLE
Container itself cannot be added when overriding a task

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#293]
Containers undefined in the task definition file are not reflected in the task even if they are defined in task_overrides.

```
clusters:
  - name: staging
    services:
      forwarder:
        ...
        task_overrides:
          container_definitions:
            - name: datadog
              image: datadog/agent:latest
```

The above code will not add a datadog container.
