### ISSUE TITLE
Environment variables are registered twice when task definitions are overwritten

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#295]
When overwriting an environment variable defined in a task, there is a problem that the variable is double registered and the value added later becomes valid.

config/deploy.yml
```yaml
# config/deploy.yml
...
task_overrides:
  container_definitions:
    - name: app
      environments:
        - name: FOO
           value: override

# config/deploy/xxx.yml
container_definitions:
  ...
  container_definitions:
    name: app
    environments:
      - name: foo
        image: foo
```

Environment variables are expanded as follows
```yaml
environments:
  - name: foo
    image: foo
  - name: foo
    image: override
```
