### ISSUE TITLE
"family" parameter cannot be overridden by task override

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#299]
Family name different from the task definition is specified for the "task_overrides" parameter, an `CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "***.dkr.ecr.ap-northeast-1.amazonaws.com/staging-worker-rails:build-20220619-123942": ***.dkr.ecr.ap-northeast-1.amazonaws.com/staging-worker-rails:build-20220619-123942: not found (Genova::Exceptions::TaskStoppedError) ERROR: 1` error occurs.

```
  services:
    worker:
      containers:
      - name: rails
        build:
          context: ..
      path: ./deploy/backend/staging.yml
      task_overrides:
        family: staging-worker
```
