### ISSUE TITLE
Supports target option during build

### ISSUE THREAD

**Issue by JunyaSatou** [metaps/genova#382]
docker-compose.ymlで

```yaml
app:
    container_name: kaihipay-customer-frontend
    build:
      context: .
      dockerfile: ./infra/docker/web/Dockerfile
      target: ${BUILD_TARGET}
      args:
        APP_ENV: ${APP_ENV}
        SERVER_NAME: ${SERVER_NAME}
```

とし target に指定した値は有効であることを確認済み。

genovaで

```yaml
clusters:
  - name: mpfront
    services:
      kaihipay-customer-frontend-development:
        containers:
          - name: web
            build:
              context: ../../..
              dockerfile: ./infra/docker/web/Dockerfile
              args:
                APP_ENV: development
                ENV_FILE: .env.development
                SET_REAL_IP_FROM: 172.30.0.0/16
                SERVER_NAME: kaihipay-member.mpfront.com
              target: development
        path: ./deploy/development/service.yml
```
のように targetパラメータ指定したが有効ではなさそうだった（※2022年11月ごろ時点）。
genovaでtarget パラメータは有効でしょうか。

やりたいこと「マルチステージビルド」
https://matsuand.github.io/docs.docker.jp.onthefly/develop/develop-images/multistage-build/
