### ISSUE TITLE
Filtering Functionality for Deployment Branches

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#425]
デプロイ時に指定可能なブランチをフィルタリングする機能を追加したい。

```yaml
# config/settings.local.yml
github:
  restricts:
    - resource: cluster
      name: 'production-*'
      branches:
        - main
        - 'release/*'
```
