### ISSUE TITLE
1リポジトリで複数のデプロイ定義を登録できるようにしたい

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#97]
## 概要
1リポジトリから複数のサービスをデプロイできるようにしたい。

```
- repo_A
  |- config/deploy.yml
```
```
- repo_B
  |- microservice_a
    |- config/deploy.yml
  |- microservice_b
    |- config/deploy.yml
  |- microservice_c
    |- config/deploy.yml
```

config/settings.local.ymlは次のようなイメージ。

```
github:
  repositories:
    - name: repo_A
      base_path: .
    - name: repo_B
      base_path: ./microservice_a
      alias: microservice_a
    - name: repo_B
      base_path: ./microservice_b
      alias: microservice_b
    - name: repo_B
      base_path: ./microservice_c
      alias: microservice_c
```
CLIデプロイ時はaliasを引数に`microservice_*`を指定。

## Tasks

* [x] Slack
  * [x] deploy
  * [x] redeploy
  * [x] history
* [x] CLI
